[package]
name = "egui_clickpack_db"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.28"
egui_extras = "0.28"
fuzzy-matcher = "0.3.7"
humansize = "2.1.3"
indexmap = { version = "2.2.6", features = ["serde"] }
log = "0.4.22"
open = "5.2.0"
serde = "1"
serde_json = "1"
zip-extract = { version = "0.1.3", default-features = false, features = ["deflate"] }

[features]
default = []
live = []
